import { z } from 'zod';
import { IDatabaseAdapter, TableDefinition, FilterOperator, QueryAST } from './Table';
import { IServiceBroker, ContextStack, MeshError } from '@flybyme/isomorphic-core';

/**
 * Extracts the raw object shape from a Zod Schema for use in the Builder.
 */
export type TableSchema<T extends z.AnyZodObject> = z.infer<T>;

/**
 * Narrowing type for Column Selection.
 * Ensures you can only select keys that actually exist on the Zod object.
 */
export type ColumnOf<T extends z.AnyZodObject> = keyof TableSchema<T>;

interface Filter {
    column: string;
    operator: FilterOperator;
    value: unknown;
}

/**
 * QueryBuilder — A type-safe fluent interface for database operations.
 */
export class QueryBuilder<T extends z.AnyZodObject, R = z.infer<T>> {
    private selectedColumns: string[] = [];
    private filters: Filter[] = [];
    private limitValue?: number;
    private offsetValue?: number;
    private tenantIdOverride?: string;
    public name: string;

    constructor(
        private readonly table: TableDefinition<T>,
        public readonly adapter: IDatabaseAdapter,
        private readonly enforceTenancy: boolean = false,
        private readonly broker?: IServiceBroker
    ) {
        this.name = table.name
    }

    private clone(): QueryBuilder<T, R> {
        const cloned = new QueryBuilder(this.table, this.adapter, this.enforceTenancy, this.broker);
        cloned.selectedColumns = [...this.selectedColumns];
        cloned.filters = [...this.filters];
        cloned.limitValue = this.limitValue;
        cloned.offsetValue = this.offsetValue;
        cloned.tenantIdOverride = this.tenantIdOverride;
        return cloned as QueryBuilder<T, R>;
    }

    /** Set the tenant context for this query (overrides dynamic context) */
    forTenant(id: string): QueryBuilder<T, R> {
        const next = this.clone();
        next.tenantIdOverride = id;
        return next;
    }

    /** Select specific columns */
    select<K extends ColumnOf<T>>(columns: K[]): QueryBuilder<T, Pick<TableSchema<T>, K>> {
        const next = this.clone() as QueryBuilder<T, Pick<TableSchema<T>, K>>;
        next.selectedColumns = columns as string[];
        return next;
    }

    /** Add a where clause with type-safe value checking */
    where<K extends ColumnOf<T>>(
        column: K,
        operator: FilterOperator,
        value: TableSchema<T>[K]
    ): QueryBuilder<T, R> {
        return this.internalWhere(column as string, operator, value);
    }

    /** Internal where for dynamic usage by mixins/infrastructure */
    internalWhere(column: string, operator: FilterOperator, value: unknown): QueryBuilder<T, R> {
        const next = this.clone();
        next.filters.push({ column, operator, value });
        return next;
    }

    limit(n: number): QueryBuilder<T, R> {
        if (!Number.isInteger(n) || n < 0) {
            throw new Error(`Limit must be a non-negative integer, got: ${n}`);
        }
        const next = this.clone();
        next.limitValue = n;
        return next;
    }

    offset(n: number): QueryBuilder<T, R> {
        if (!Number.isInteger(n) || n < 0) {
            throw new Error(`Offset must be a non-negative integer, got: ${n}`);
        }
        const next = this.clone();
        next.offsetValue = n;
        return next;
    }

    private toAST(): QueryAST {
        const tenantId = this.enforceTenancy ? this.getTenantId() : this.tenantIdOverride;
        
        if (this.enforceTenancy && !tenantId) {
            throw new Error(`Tenant ID resolution failed while enforceTenancy is active for table: ${this.table.name}`);
        }

        // Validate limit/offset again just in case internal mutations bypassed methods
        if (this.limitValue !== undefined && (!Number.isInteger(this.limitValue) || this.limitValue < 0)) {
            throw new Error(`Invalid limit value: ${this.limitValue}`);
        }
        if (this.offsetValue !== undefined && (!Number.isInteger(this.offsetValue) || this.offsetValue < 0)) {
            throw new Error(`Invalid offset value: ${this.offsetValue}`);
        }

        return {
            table: this.table.name,
            select: this.selectedColumns.length > 0 ? [...this.selectedColumns] : undefined,
            filters: [...this.filters],
            limit: this.limitValue,
            offset: this.offsetValue,
            tenantId
        };
    }

    /** Finalize insert with optional conflict handling */
    async executeInsert(data: Partial<z.infer<T>>): Promise<{ id?: number | string }> {
        // Validate against schema
        const validated = this.table.schema.partial().parse(data);

        // Strip ID - it must be generated by the adapter or system
        const payload = { ...(validated as unknown as Record<string, unknown>) };
        delete payload.id;

        // Add tenant_id if required
        if (this.enforceTenancy) {
            const tid = this.getTenantId();
            if (!tid) {
                throw new Error(`Tenant ID resolution failed for insert into table: ${this.table.name}`);
            }
            payload.tenant_id = tid;
        }

        const res = await this.adapter.insert(this.table.name, payload as Record<string, unknown>);

        this.notifyMutation('insert');
        return { id: res.lastInsertId };
    }

    /** Legacy insert renamed to support chain */
    async insert(data: Partial<z.infer<T>>): Promise<{ id?: number | string }> {
        return this.executeInsert(data);
    }

    /** Update data with filters and validation */
    async update(data: Partial<z.infer<T>>): Promise<{ changes: number }> {
        const ast = this.toAST();

        // Bulletproof Mutation Guard
        if (ast.filters.length === 0 && !ast.tenantId) {
            throw new MeshError({
                message: `Destructive update prevented: No filters or tenant context provided for table ${this.table.name}`,
                code: 'DESTRUCTIVE_OPERATION',
                status: 403
            });
        }

        const validated = this.table.schema.partial().parse(data);
        const payload = { ...(validated as unknown as Record<string, unknown>) };
        delete payload.id;

        if (Object.keys(payload).length === 0) {
            return { changes: 0 };
        }

        const res = await this.adapter.update(ast, payload as Record<string, unknown>);

        this.notifyMutation('update');
        return { changes: res.changes };
    }

    /** Delete records matching current filters */
    async delete(): Promise<{ changes: number }> {
        const ast = this.toAST();

        // Bulletproof Mutation Guard
        if (ast.filters.length === 0 && !ast.tenantId) {
            throw new MeshError({
                message: `Destructive delete prevented: No filters or tenant context provided for table ${this.table.name}`,
                code: 'DESTRUCTIVE_OPERATION',
                status: 403
            });
        }

        const res = await this.adapter.delete(ast);

        this.notifyMutation('delete');
        return { changes: res.changes };
    }

    private static queryQueue: Map<string, { sql: string, params: unknown[], resolve: (val: unknown) => void }[]> = new Map();

    /**
     * Transaction Context: Ensures nested calls use the same transaction.
     */
    public async transaction<R>(fn: (qb: this) => Promise<R>): Promise<R> {
        const ctx = this.broker?.getContext() || ContextStack.getContext();
        const existingTx = (ctx?.meta as { _tx?: boolean })?._tx;

        if (existingTx) {
            return await fn(this);
        }

        if (!this.adapter.transaction) {
            return await fn(this);
        }

        return await this.adapter.transaction(async () => {
            // Create a new context with the transaction handle
            const txCtx = Object.assign(Object.create(ctx || {}), ctx, {
                meta: { ...ctx?.meta, _tx: true }
            });

            return await ContextStack.run(txCtx, () => fn(this));
        });
    }

    /**
     * Query Debouncing: Batch rapid SELECTs to reduce WASM overhead.
     */
    private async executeDebounced(): Promise<R[]> {
        // const _key = `${this.table.name}:${JSON.stringify(this.filters)}`;
        // Future implementation: wait 10ms, group same queries
        return this.execute();
    }

    /**
     * Batch execution to reduce WASM overhead.
     */
    public async batch(operations: (qb: this) => Promise<void>): Promise<void> {
        return this.transaction(operations);
    }

    private notifyMutation(type: string): void {
        if (this.broker) {
            this.broker.emit(`$db.${this.table.name}.mutated`, {
                type,
                table: this.table.name,
                tenantId: this.getTenantId()
            });
        }
    }

    /** Finalize and execute the SELECT query */
    async execute(): Promise<R[]> {
        const rows = await this.adapter.find<unknown>(this.toAST());

        // Task 15: Perform runtime validation (optional mapping)
        // If we selected specific columns, we can't use the full schema validation
        // unless we use a partial schema or a dynamic one.
        if (this.selectedColumns.length === 0) {
            return rows.map(row => this.table.schema.parse(row)) as R[];
        }

        // If specific columns are selected, we should ideally still parse with a picked schema
        const partialSchema = this.table.schema.pick(
            Object.fromEntries(this.selectedColumns.map(c => [c, true])) as Record<string, true>
        );
        return rows.map(row => partialSchema.parse(row)) as R[];

    }

    /** Count records matching current filters */
    async count(): Promise<number> {
        return this.adapter.count(this.toAST());
    }

    private getTenantId(): string | undefined {
        const context = this.broker?.getContext() || ContextStack.getContext();
        const meta = context?.meta as { user?: { tenant_id?: string }, tenant_id?: string } | undefined;
        const dynamicTenantId = meta?.user?.tenant_id || meta?.tenant_id;
        return this.tenantIdOverride || dynamicTenantId;
    }
}
