/**
 * generateNodeShims
 * Provides a virtual file containing polyfills for common Node.js APIs 
 * that isomorphic code might expect, even when running in a browser mesh.
 */
export function generateNodeShims(): string {
    return `
/**
 * Mesh Isomorphic Node Shims
 * Generated by isomorphic-compiler
 */

// 1. Process Shim
if (typeof process === 'undefined') {
    (window as any).process = {
        env: { NODE_ENV: 'development' },
        browser: true,
        version: 'v20.0.0',
        nextTick: (fn: any, ...args: any[]) => setTimeout(() => fn(...args), 0),
        cwd: () => '/',
        platform: 'browser'
    };
}

// 2. Buffer Shim (If needed, otherwise use native Uint8Array)
if (typeof Buffer === 'undefined') {
    // Basic shim or link to a bundle
}

// 3. Path Shim (Minimal)
if (typeof (window as any).path === 'undefined') {
    (window as any).path = {
        join: (...parts: string[]) => parts.filter(Boolean).join('/').replace(/\\/\\/+/g, '/'),
        resolve: (...parts: string[]) => '/' + parts.filter(Boolean).join('/').replace(/\\/\\/+/g, '/'),
        dirname: (p: string) => p.split('/').slice(0, -1).join('/') || '/',
        basename: (p: string) => p.split('/').pop() || '',
        extname: (p: string) => {
            const b = p.split('/').pop() || '';
            const i = b.lastIndexOf('.');
            return i < 0 ? '' : b.slice(i);
        }
    };
}

// 4. Global Shims
(window as any).global = window;
    `;
}
